import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Outfit } from 'next/font/google'
import CookiesBanner from "./components/CookiesBanner";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-outfit',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={outfit.className}
      >
        {children}
      </body>
      <CookiesBanner/>
    </html>
  );
}
