import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import 'animate.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '600'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased text-white scroll-smooth overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
